StasDoskalenko/react-native-google-fit

- README.md
- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- android/src/main/java/com/reactnative/googlefit/GoogleFitPackage.java
With this code I am able to install the module using the update install instructions on React Native 0.41.
> Get activity correctly and automatically

- .gitignore
- android/src/main/AndroidManifest.xml
- android/src/main/java/com/reactnative/googlefit/DistanceHistory.java
- android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java
- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- index.js
> Added method to read distance

- README.md
- android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java
- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- index.android.js
Fixes periodical exception:
```
Exception java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
```
> Replaces invocation with event emittion

- README.md
Hi,
just a little clean up on the readme for the lisibility :)
> README lisibility

- index.android.js
> Convert class methods to arrow functions

- android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java
> Fix the problem with wrong value of isAuthorized()

- README.md
- android/src/main/java/com/reactnative/googlefit/ActivityHistory.java
- index.android.js
+ small refactor and remove useless comments
> update README for new functionality. 

- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- android/src/main/java/com/reactnative/googlefit/RecordingApi.java
- index.android.js
Will have the ability to pass data types for recording API
> Adding parameters for recording API

- android/src/main/java/com/reactnative/googlefit/BodyHistory.java
I've found that getWeightSamples where broken. There was "java.lang.IllegalStateException: Must specify a valid bucketing strategy while requesting aggregation" error.
> Fix retrieving weight samples.

- android/build.gradle
Additional testing required. Any help is needed! 👍
> Update to the newest SDKs, fix Gradle errors

- README.md
Added response JSON examples for several methods
> Updated README with more documentation

- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- android/src/main/java/com/reactnative/googlefit/StepHistory.java
- index.android.d.ts
- index.android.js
Expose function getUserInputSteps so we could get only user input steps.
In my case, I need to use step from `aggregateDataByDate` and minus it with user input steps.
> Add function getUserInputSteps

- index.android.d.ts
- index.android.js
Mostly based on the documentation. Also remove some util functions that were mentioned in the typings.
Also - `deleteHeight` was actually calling `deleteWeight`, so I fixed that as well
> Add some more typings

- README.md
- android/src/main/java/com/reactnative/googlefit/BodyHistory.java
- android/src/main/java/com/reactnative/googlefit/CalorieHistory.java
- android/src/main/java/com/reactnative/googlefit/DistanceHistory.java
- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- android/src/main/java/com/reactnative/googlefit/HeartrateHistory.java
- android/src/main/java/com/reactnative/googlefit/HelperUtil.java
- android/src/main/java/com/reactnative/googlefit/NutritionHistory.java
- android/src/main/java/com/reactnative/googlefit/StepHistory.java
- index.android.d.ts
- index.android.js
This allows the caller to determine how they want to bucket the aggregated data.
> Bucket settings

- README.md
- android/src/main/AndroidManifest.xml
this lifts the responsibility of location permission handling to the user instead of the library. See here: https://github.com/StasDoskalenko/react-native-google-fit/pull/194#issuecomment-719971344
> [loc_perm_lift] lift location perm responisbility

- README.md
- android/src/main/java/com/reactnative/googlefit/ActivityHistory.java
- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- android/src/main/java/com/reactnative/googlefit/HelperUtil.java
- android/src/main/java/com/reactnative/googlefit/StepHistory.java
- index.android.d.ts
- index.android.js
1. add getMoveMinutes() to retrieve Move Minutes data.
Solve #232 
2. Refactor  duplicate `processDataSet()` function in stepHistory
Example Result: 
```json
[
{
"dataSourceId":"derived:com.google.active_minutes:com.google.android.gms:aggregated",
"dataTypeName":"com.google.active_minutes",
"duration":73,
"endDate":1622594700000,
"originDataSourceId":"derived:com.google.step_count.delta:com.google.android.gms:estimated_steps",
"startDate":1622574300000
},
{
"dataSourceId":"derived:com.google.active_minutes:com.google.android.gms:aggregated",
"dataTypeName":"com.google.active_minutes",
"duration":0,
"endDate":1622675040000,
"originDataSourceId":"raw:com.google.active_minutes:com.google.android.apps.fitness:user_input",
"startDate":1622671440000
},
{ …
```
> Feature: getMoveMinutes()

- README.md
- android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java
- docs/INSTALLATION.md
- package-lock.json
- package.json
Based on #85 & #243, partial credits belong to @moulie415 for Datapoint field
```js
GoogleFit.saveWorkout({
startDate: startDate,
endDate: endDate,
sessionName: `session name`,
identifier: `session:${Date.now()}-${dataType}:${startDate}-${endDate}`, // UUID
activityType: ActivityType.Meditation, //dataType
description: `some description`,
// options field
calories: 233, // most consistent field across all activities
steps: 600, // may not working, for example: ActivityType.Meditation doesn't have step by default
// experimental field
// this may not work or overwrite by GoogleFit App, it works in ActivityType.Other_unclassified_fitness_activity
intensity: 1 // display as heart points in Google Fit app
});
```
There are close to 100 activities but I cannot test them one by one, and seems …
> workout support [experimental]

- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- android/src/main/java/com/reactnative/googlefit/HealthHistory.java
- index.android.d.ts
- index.android.js
Need to be able to save blood pressure readings for a current project. Have working locally with a clone of the repo. Use #137 and existing features as a guide. Let me know if there's anything else I need to do!
Related comment: https://github.com/StasDoskalenko/react-native-google-fit/pull/137#issuecomment-1176839064
> Added support for saving blood pressure

- README.md
- android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
- android/src/main/java/com/reactnative/googlefit/HealthHistory.java
- index.android.d.ts
- index.android.js
Added Support for Resting Heart Rate (Same scope as Heart Rate)
> Added Resting Heart Rate Support

- .github/workflows/create-release-branch.yml
- .github/workflows/publish-npm.yml
- .github/workflows/release-published.yml
```mermaid
flowchart TD
Start([Start Release]) --> Manual1[/"👤 Step 1: Create Release Branch<br/>(Manual - GitHub Actions)"/]
Manual1 --> Action1["🔧 Workflow: create-release-branch.yml<br/>• Calculate new version<br/>• Create release/vX.Y.Z branch<br/>• Push git tag vX.Y.Z"]
Action1 --> Manual2[/"👤 Step 2: Publish Release<br/>(Manual - GitHub UI)"/]
Manual2 --> Action2["📝 On GitHub Releases:<br/>• Draft new release<br/>• Select tag vX.Y.Z<br/>• Generate release notes<br/>• Edit if needed<br/>• Publish release"]
Action2 --> Auto1["⚡ Workflow: release-published.yml<br/>(Automatic)<br/>• Get release notes<br/>• Update package.json<br/>• Update CHANGELOG.md<br/>• Create release-pr/vX.Y.Z branch<br/>• Open PR to master"]
Auto1 --> Manual3[/"👤 Step 3: Review & Merge PR<br/>(Manual)"/]
Manual3 …
```
> Document releases flow
