android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java, android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java, android/src/main/java/com/reactnative/googlefit/RecordingApi.java, index.android.js
Record steps and distance without the need for third-party apps.  Simply call ```GoogleFit.startRecording()```  after authorizing.
The function need only be called once but can be called multiple times (Perhaps every time the app is opened).  Once called, the Recording API is initialized for selected fitness data types and will be reinitialized when the mobile device reboots.
=> Add Recording API

android/build.gradle
To make this work on React Native v0.56.0 and later projects, the Android API version needs to be updated to at least 25. The `safeExtGet` function implemented will get the config from React Native project's main `build.gradle` file to use the project version else if `ext` is not available, it will use API 23. This won't affect the projects currently using this package with API 23.
=> RN v56+ changes

android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java, android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java, index.android.js, src/scopes.js
Currently, the requested scopes are hardcoded and can't be configured or changed, this leads to UX issued (it could be suspicious when the application requests permission to access the blood pressure data if it is not needed).
So, this PR adds an ability to configure scopes through adding `options` params to the `authorize` method, and the function can be called as:
```
GoogleFit.authorize({
scopes: [
Scopes.FITNESS_ACTIVITY_READ_WRITE,
Scopes.FITNESS_BODY_READ_WRITE,
],
});
```
It has compatibility with the previous version because if scopes are not provided it uses the same scope as the current version of this lib.
Also, I've added `Scopes` export with all the available scopes.
@StasDoskalenko please, let me know what you think. I'll add documentation if the PR is ok.
Also, I think this …
=> Ability to pass custom Scopes

android/src/main/java/com/reactnative/googlefit/BodyHistory.java
Some improvements for retrieving weights data:
- Improve granularity down to as little as 1 minute
- Always get FIELD_AVERAGE to maximise the match the value reported in the Google Fit app for most phone models
=> Improve weights granularity and always use FIELD_AVERAGE

android/build.gradle
With the latest update to google play services, `androidx` has been used as default instead of `support library`. Due to this, the older apps are failing to build because the latest play services require the apps to use `androidx`. `androidx` and `support library` do not work together. So, this PR provides applications to specify play services auth and fitness versions.
https://developers.google.com/android/guides/releases#june_17_2019
=> use auth and fitness versions from root projects if available

android/src/main/java/com/reactnative/googlefit/BodyHistory.java
The height history had the following bug:
```
average(f) not a field of DataType{com.google.height[height(f)]}
```
=> Fixed height computation

react-native.config.js
Adds a react-native.config.js file which controls how the package is instantiated and passes BuildConfig.APPLICATION_ID arg to GoogleFitPackage() constructor in PackageList.java
=> Adds support for React Native 60 PackageList.java

android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java, android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java
The disconnect method was using an old API and presented an unpredictable behaviour.
By making use of the GoogleSignInClient class we can assure the user's Google account will indeed be disconnected from the app.
=> fixed disconnect method

index.android.d.ts
The JavaScript API provides a boolean called `isAuthorized` that is `true` when the user has authorized Google Fit on their device. Unfortunately, this boolean is not exposed in the TypeScript API. This PR amends that.
=> Expose isAuthorized boolean in TypeScript

android/src/main/java/com/reactnative/googlefit/HeartrateHistory.java
Currently this library is unable to read more than 5 heart rate records at a time using `getHeartRateSamples`. I believe this is because the original code for `HeartrateHistory` was based on `BodyHistory` but accidentally carried over some unnecessary code. I have removed the 5 record limit and updated some of the comments in `HeartrateHistory` to be more accurate.
Fixes #121
=> Fix heart rate read limit

README.md, android/src/main/AndroidManifest.xml, android/src/main/java/com/reactnative/googlefit/RecordingApi.java, index.android.d.ts, index.android.js, src/utils.js
A better approach for #142,  instead of simply removing the distance to avoid any sensitive permissions ask for android 6.0+ (that can cause a crash).
Allow to pass argument as following,
GoogleFit.startRecording( callback => {
console.log(callback);
// Process data from Google Fit Recording API (no google fit app needed)
}, ['step','distance']);
Permission panel will be promoted, if permission is denied, remove `distance` from record list to ensure others still get subscribed. 
Note: Permission panel will always pop out on run time if `GoogleFit.startRecording ` with `distance` argument is called on your code, until user select `"never ask again"`.
Step recording now matches the correct DataType as Google Fit App for general use and `readMe` doc, but it may break if someone do use the …
=> Fix and modify recording api for step, typescript and allow to ask permission for distance

android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java, android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java, android/src/main/java/com/reactnative/googlefit/SleepHistory.java, index.android.d.ts, index.android.js, package.json, src/utils.js
This PR adds support for Google Fit Sleep data. I ended up adding a dev dependency for MomentJS because Android was crashing on invalid dates coming back from the sleep data samples. Using moment instead of "new Date()" to parse those incoming dates fixes the crash.
=> Add Sleep Data support

README.md, android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java, android/src/main/java/com/reactnative/googlefit/StepHistory.java, index.android.d.ts, index.android.js, src/utils.js
Just fewer update to further enhance StepHistory.
1. Remove deprecated week and day method from java file since they all migrated to Javascript previously, are not accessible anywhere even in the past.
2. Fix existing date issue with `getdaily/weeklyStep`, which will return inaccurate step data. The default always respect to your local timezone.
3. Migrated deprecated step api to standard api.
New feature: 
`rawSteps` is introduced to tackle some issues #167, #160, 
`options` for `getDailyStepCountSamples`, `getdaily/weeklyStep` now has a options config to get details based on your need
For instance:
const dailyOptions = {
startDate: moment(today).startOf('day'),
endDate: moment(today).endOf('day'),
// configs:{
//   bucketTime: 15,
//   bucketUnit: 'MINUTE' | 'HOUR' | 'SECOND' | 'DAY' …
=> Feat. Update, remove and updated deprecated step Api.

android/src/main/java/com/reactnative/googlefit/SleepHistory.java
**This PR includes code to handle an exception that prevents users to read sleep data, in some scenarios google fit is not able to read sleep records.**
when the app is facing for this error, google fit response  `4: The user must be signed in to make this API call.` as error message, after some research, we figured out that was possible to request specific permission by using `GoogleSignIn.requestPermissions`,  so following that way we were able to fix this issue by requesting permissions when the app turns on that error.
we also figured out that the app gets this error after we manually removed the permission from Google fit app, in that scenario after we remove the permissions and we back to the app and started the sync process google fit was not able to get all the required …
=> Handle permissions exception for google fit

src/scopes.js
Hi there, I have found that requesting heart rate data requires the heart rate scopes.
I was getting only an empty array for heart rate and decided to debug with Android Studio's logcat, there I saw this message:
`2021-01-25 15:27:56.381 24173-12564/? W/Fitness: Failed to authenticate com.pruebareact: Status{statusCode=Application needs OAuth consent from the user, resolution=PendingIntent{9cb3585: android.os.BinderProxy@fb27fda}} [CONTEXT service_id=17 ]
`
So I went to [https://developers.google.com/fit/datatypes#authorization_scopes](url) and manually added 'https://www.googleapis.com/auth/fitness.heart_rate.read' to the `options.scopes` and everything worked fine!
I'm not sure if this is something new with Google Fit API, but it's the only way I could get this data. Other kinds of data …
=> Add heart rate scopes

android/src/main/java/com/reactnative/googlefit/HelperUtil.java, android/src/main/java/com/reactnative/googlefit/StepHistory.java, index.android.d.ts
When trying this library with Google Fit and my smart watch, I noticed that the returned steps data does not have any device info available.
Depending on where the data comes from, the device information can be found by calling `dp.getOriginalDataSource().getDevice()`. This PR adds that information to the response when available.
To me it looks like the Typescript types in the current version are not up-to-date, so I tried updating them, but I'm not sure if I did it correctly. Please let me know if you think that they are not correct.
P.S.
There are also other fields that could be added with a separate Pull Request, e.g. `dp.getOriginalDataSource().getAppPackageName()` and the `appName` when the data comes from a third-party app, such as Withings Health Mate or Polar Flow.
@aboveyunhai
=> Add device info to the data when available

android/src/main/java/com/reactnative/googlefit/ActivityHistory.java, android/src/main/java/com/reactnative/googlefit/HelperUtil.java, android/src/main/java/com/reactnative/googlefit/StepHistory.java, index.android.d.ts
In my previous Pull Request I added device information to the data when it is available. The fit data might not be synced from a device directly, but instead from a 3rd party app. In that case it would be useful to know from which app the data is coming from.
This Pull Request adds a call to `dp.getOriginalDataSource().getAppPackageName()` to get the source's app package name if available. In the case where the package name is set, we can use the package manager to get the name of that app.
I tested these changes with my test app and the Withings Health Mate app, and here is how the data looks like.
**Data from Withings watch and the Health Mate app installed:**
```js
appName: "Health Mate",
appPackageName: "com.withings.wiscale2",
...
```
**Data from Withings watch and no app installed …
=> Add app info to the data

package-lock.json, package.json
Rely on semantic versioning (https://docs.npmjs.com/about-semantic-versioning)
This makes it a lot easier to apply security updates in projects that use react-native-google-fit without needing to push an update of react-native-google-fit every time a dependency is updated.
Also adds `react-native` as a [peer dependency](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies).
=> Relax the version requirements

android/src/main/java/com/reactnative/googlefit/CalorieHistory.java, android/src/main/java/com/reactnative/googlefit/HealthHistory.java, index.android.d.ts
This improvement allows methods related to the `HeathHistory` module and `CalorieHistory` module to return a key called `wasManuallyEntered` for each data point received. This tells us if the user has added that data directly in Google Fit ( in which case `wasManuallyEntered: true`), or if it was recorded with a sensor by a watch, band etc ( in which case `wasManuallyEntered: false`).  This is beneficial for cases when you need to get the actual data ( if you give rewards on workouts or you use it for some sort of competition ).
The methods that will benefit from this are: `getDailyCalorieSamples`,`getHeartRateSamples`, `getBloodPressureSamples`, `getBodyTemperatureSamples`, `getOxygenSaturationSamples`, `getBloodGlucoseSamples`.
A similar issue was reported in #39 , though it's old.
=> Flag manually added data on CalorieHistory & HealthHistory

android/build.gradle, android/gradle.properties
Hi, I'm not used to this kind of PRs so please tell me if my change is wrong.
Jetifier being deprecated, we need to migrate libs to AndroidX:
- Use AndroidX by default but keep backwards compatibility with `supportLibVersion`.
- Bump sdk version to 28 (needed for AndroidX)
=> Use AndroidX

android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java, android/src/main/java/com/reactnative/googlefit/HealthHistory.java, index.android.d.ts, index.android.js, src/utils.js
This defaults to false (existing behaviour) so is backwards compatible.
When inLocalTimeZone = false, dates are returned in the format: "endDate":"2022-12-22T16:51:30.000Z" When inLocalTimeZone = true, dates are returned in the format: "endDate":"2022-12-22T11:51:30.000-0500"
This allows performance improvements, because you don't have to perform further date processing on the values to convert them back into the local time zone.
This PR adds the flag as a parameter to getSleepSamples. It can easily be added to other functions as required.
=> Added the inLocalTimeZone parameter to the prepareResponse function.

android/src/main/java/com/reactnative/googlefit/ActivityHistory.java, index.android.d.ts
Resolves #357 
Save Workout did not include distance which is an odd api choice because fetch workout does include distance. For my own personal needs adding distance to workout saving was necessary and i imagine it will be valuable to other users as well. I did mention a notice of missing permissions somewhere in the code but i tested this code and it works as is. Modeled it after the way calories and intensity are optionally added into the save workout payload. 
Mention in comments about permission restriction
https://github.com/StasDoskalenko/react-native-google-fit/blob/master/android/src/main/java/com/reactnative/googlefit/ActivityHistory.java#L390
```
// distance scope is missing here due to permission restriction
// will be added in the future while distance is also available from …
```
=> Improvement: Add Distance to saveWorkout, to match workout fetching.
